FROM node:19.1.0-alpine3.16

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
RUN yarn install

COPY . .

RUN yarn global add ts-node
RUN yarn global add typescript

EXPOSE 3001

CMD [ "yarn" , "dev"]


