FROM node:19.1.0-alpine3.16

WORKDIR /app

COPY package*.json tsconfig.json ./
RUN yarn install

RUN yarn global add ts-node
RUN yarn global add typescript

COPY . .

EXPOSE 3001

CMD [ "yarn" , "dev"]


