version: '3.8'

services:
    app:
        build: './client'
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
    auth-server:
        build: './services/auth'
        ports:
            - 3001:3001
        environment:
            MONGO_URL: mongodb+srv://moon:moon123@cluster0.4colf4i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
            JWT_SECRET: my_secret
            PORT: 3001
        volumes:
            - ./services/auth/:/app/data
volumes:
    feeds:
