version: '3.8'

services:
    web:
        build: './client'
        ports:
            - 3000:3000
        volumes:
            - ./clinet:/app

    api_auth:
        build: './services/auth'
        ports:
            - 3000:3000
        volumes:
            - ./services/auth:/app
        environment:
            DB_URL: mongodb://db/feeds

    db_auth_mongo:
        image: mongo:4.0.28-xenial
        ports:
            - 27017:27017
        volumes:
            - feeds:/data/db
volumes:
    feeds:
