# Build stage
FROM golang:alpine3.17 AS builder

WORKDIR /app
COPY . .
RUN go build -o main main.go

# Run stage
FROM golang:alpine3.17 AS runner
WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 3002
ENTRYPOINT ["/app/main"]